### ISSUE TITLE
ColorRamp in Displacement node setup hard crashes Blender (even when not rendering)

### ISSUE THREAD

**Issue by DaQuteness** [Radeon-ProRender/Blender#10]
Adding a ColorRamp node anywhere within a Displacement node chain will hard crash Blender, curiously sometimes even without rendering at all. Please see scene attached. Bypassing the ColorRamp node will allow the render to proceed.

Using Blender 2.81, RPR 2.1.1 (Core 1.34.4).

[Displacement+ColorRamp crash.zip](https://github.com/Radeon-ProRender/Blender/files/3922441/Displacement%2BColorRamp.crash.zip)

**Comment by bsavery** [comment]
I think this is fixed.  If not please reopen.
