### ISSUE TITLE
RPR 2.2.1 Preview Render Corruption on Object Click

### ISSUE THREAD

**Issue by aledbrown** [Radeon-ProRender/Blender#14]
Simply clicking between 3D mesh objects in a scene running RPR preview causes terrible blocky corruption on the screen.

Video link:
https://streamable.com/1gn6s

Blender file:
[01 RPR Test File v1.blend.zip](https://github.com/Radeon-ProRender/Blender/files/4025946/01.RPR.Test.File.v1.blend.zip)

**Comment by jamespa16** [comment]
I too get that; seems that it is even easier to cause by clicking back and forth between the scene graph and the viewport preview. More objects usually result in less squares, with just the default cube it goes almost completely black instantly. As usual though, just wiggling the camera a little bit refreshes the viewport and they go away for the time being. Click on the scene graph and back to the viewport for them to come back though!

**Comment by aledbrown** [comment]
I've isolated the Preview Viewport Cubic Screen Corruption down to Noise Threshold has to be > 0.00 and Limit Viewport Resolution has to be Ticked. It's Limit Viewport Resolution that causes the issue not NT per say. If you turn Limit Viewport Res off then Noise Threshold can be greater than 0.00 and it's fine. This is only tested with 1 GPU. Either a dGPU or an eGPU. Same result.

When Limit Viewport Resolution is ticked the Noise Threshold setting actually controls the amount of cubic corruption on the screen.

**Comment by bsavery** [comment]
Thanks.  Yes there is a regression in RPR SDK that we found and fixed already that was causing this!  Next version will be fixed, but please reopen if you see it again.
