### ISSUE TITLE
RPR 2.2.1 Random Crash for Checker Node

### ISSUE THREAD

**Issue by aledbrown** [Radeon-ProRender/Blender#15]
Simply trying to connect up a checker node with an active RPR preview running causes Blender to crash.

Video:
https://streamable.com/5t61m

Re-opening Blender and re-adding the same node with preview running works fine.

Blender file:
[01 RPR Test File v1.blend.zip](https://github.com/Radeon-ProRender/Blender/files/4025949/01.RPR.Test.File.v1.blend.zip)

**Comment by bsavery** [comment]
Ok I can try and re-create this.  However do you get an error if doing this with blender started from terminal, in case we can't recreate?

**Comment by bsavery** [comment]
So yes.  I can't reproduce this.  
Here's what I did:
1.  Remove checker on left sphere.  
2.  Start preview
3.  Add checker node and connect.

What is the error if you start blender from the command line?

**Comment by aledbrown** [comment]
I've also tried to recreate this bug but I can't so I've not got an error yet. Good job for video evidence. 

I think it might be best to start from scratch rather than taking the node off and re-adding it. At that point the shaders have been compiled for that node.

It's when the shader compile is fresh that it probably happens.

**Comment by bsavery** [comment]
Hmm, well that's not exactly how RPR shader compilation works.  But I'll keep trying to reproduce.  Which GPU are you using for the preview when this happens?

**Comment by bsavery** [comment]
Is this still reproducible?
