### ISSUE TITLE
RPR 2.2.12 Noise Threshold Bugs

### ISSUE THREAD

**Issue by aledbrown** [Radeon-ProRender/Blender#16]
With this latest version the Noise Threshold setting is very broken indeed.

In preview mode the black cubes are still present when clicking between objects.

But what's worse now is that in Final Render setting Noise Threshold to any setting other than 0.00 actually makes the render take LONGER.

I haven't got time to collect all my testing together here at the moment but I wanted to make it known that further testing is required for the **Adaptive Sampling** feature.

With multi GPUs I haven't had any crashes with the latest build. However I do still get tearing of the preview where there is an obvious difference to one half of the preview. One side gets one noise level and the other side gets a much worse noise level. It makes preview with mGPU unusable still. And because turning on NT will make cubes appear in preview eventually it's back to 0.00 NT and single GPU.

**Comment by bsavery** [comment]
For the record, the feature you're talking about is called "Adaptive sampling".  The noise threshold is just the control on it.

**Comment by aledbrown** [comment]
But it only goes wonky when you change the Noise Threshold setting.

**Comment by bsavery** [comment]
thanks.  We actually fixed this on the RPR side, but there was a miscommunication and we need to set something in the plugin to enable the fix.  Sorry about that.  Should have a fix in the next day or so.

**Comment by bsavery** [comment]
Marking this as closed.

**Comment by aledbrown** [comment]
This still isn't fixed.

This is 0.2 NT with 1 GPU (notice the time and noise level in the render)
<img width="1488" alt="1 GPU" src="https://user-images.githubusercontent.com/690500/74813973-2b472b80-52ee-11ea-8cf2-c97a79fa2e36.png">

Now with 2 GPUs same settings: (notice how the noise is about 2x less but the time is slightly longer).
<img width="1488" alt="2 GPUs" src="https://user-images.githubusercontent.com/690500/74813978-2e421c00-52ee-11ea-85a5-595e0e68ed5e.png">

Conclusion: the NT setting isn't being respected across multiple GPUs.

Latest RPR v2.3.4 and Blender 2.82 final. macOS 10.15.3.
