### ISSUE TITLE
RPR v2.3.4 Adaptive Sampling Bug with mGPU

### ISSUE THREAD

**Issue by aledbrown** [Radeon-ProRender/Blender#18]
Bug:
Adaptive Sampling test with Multiple GPUS.

1 GPU = 39s
2 GPU = 40s

With a different resulting noise level on final render. Despite same settings.

This is 0.2 NT with 1 GPU (notice the time and noise level in the render)
<img width="1488" alt="1 GPU" src="https://user-images.githubusercontent.com/690500/74813973-2b472b80-52ee-11ea-8cf2-c97a79fa2e36.png">

Now with 2 GPUs same settings: (notice how the noise is about 2x less but the time is slightly longer).
<img width="1488" alt="2 GPUs" src="https://user-images.githubusercontent.com/690500/74813978-2e421c00-52ee-11ea-85a5-595e0e68ed5e.png">

Conclusion: the NT setting isn't being respected across multiple GPUs.

Latest RPR v2.3.4 and Blender 2.82 final. macOS 10.15.3.

**Comment by bsavery** [comment]
Just making sure, you have the 2.3.4 version posted on amd.com and not the patched one you were working with?  

Also as I mentioned in the other thread, do you get the same results with a noise threshold of around .01?

**Comment by bsavery** [comment]
Just making sure, you have the 2.3.4 version posted on amd.com and not the patched one you were working with?  

Also as I mentioned in the other thread, do you get the same results with a noise threshold of around .01?
