### ISSUE TITLE
RPR for Blender scene issues

### ISSUE THREAD

**Issue by nyers33** [Radeon-ProRender/Blender#3]
Hi,
I would like to benchmark various cards with RPR and add the renderer to our benchmark suite. It seems that the [Classroom](https://github.com/Radeon-ProRender/Radeon-ProRender.github.io/tree/master/blender/Scenes) scene is not working with the latest Radeon ProRender for Blender edition.

Sometimes it hangs with "Warning: Scene export completed with errors" message. Sometimes it can pass the loading phase but the render is corrupted. Can someone confirm, please?
[classroom_1.txt](https://github.com/Radeon-ProRender/Blender/files/1953176/classroom_1.txt)
[classroom_2.txt](https://github.com/Radeon-ProRender/Blender/files/1953178/classroom_2.txt)
[classroom_halt.txt](https://github.com/Radeon-ProRender/Blender/files/1953179/classroom_halt.txt)

I use blender in non-GUI mode but the issue is present in normal operation as well. For a start I tested primarily CPU mode only, but a GTX 1060 has the same pink output.
![classroom](https://user-images.githubusercontent.com/37452404/39334810-86fd17ee-49b0-11e8-8f81-77213161b4af.png)

Other [scene](https://blenderartists.org/forum/showthread.php?412080-AMD-s-(ProRender)-Plugin-for-Blender-Previewed&p=3302896&viewfull=1#post3302896) can finish rendering (sometimes creates error messages) but the saved frame has black blocks in it - BMW_Benchmark_RPR
![bmw_benchmark_rpr_1](https://user-images.githubusercontent.com/37452404/39334814-8b7f2d70-49b0-11e8-83f1-c5bb65f50eba.png)
![bmw_benchmark_rpr_2](https://user-images.githubusercontent.com/37452404/39334816-8da73a52-49b0-11e8-8b35-8938f5bc9170.png)
![bmw_benchmark_rpr_3](https://user-images.githubusercontent.com/37452404/39334817-90d9264a-49b0-11e8-9595-55a4a0462cf2.png)

The bmw scene from the repo has some glitches as well + error messages.
![bmw](https://user-images.githubusercontent.com/37452404/39334826-9da21f6c-49b0-11e8-95bb-e31b08697e49.png)
[bmw_1.txt](https://github.com/Radeon-ProRender/Blender/files/1953181/bmw_1.txt)
[bmw_2.txt](https://github.com/Radeon-ProRender/Blender/files/1953182/bmw_2.txt)

OS: Win10 Version 1803 (17134.1)
blender-2.79b-windows64
RPR 1.6.152 for Blender

It would be cool to have some nice looking scenes for benchmarking purposes! There are some great renders at Radeon ProRender Gallery - lighthouse, motorcycle, robot, archiviz, etc. [Max](https://github.com/Radeon-ProRender/Max/releases/tag/sample_scenes) has some scenes as well - Dragon, Vehicle, Villa.

Can the maintainer update the [scenes](https://github.com/Radeon-ProRender/Radeon-ProRender.github.io/tree/master/blender/Scenes) so that they work with the latest release?

**Comment by bsavery** [comment]
So with the classroom scene.  I think it extensively uses referenced files.  Which means that you have to go into each file (for the desk, parts, etc) and convert the materials in them.  THEN render the main scene.

Well look at that aov setting issue.  Is it possible the scene was saved in 2.78 and then rendered only in 2.79?

**Comment by nyers33** [comment]
Oh, I thought the scenes are good to go, no need to convert materials - my bad.

As the scenes were uploaded more than a year ago they must have been saved with 2.78. RPR plugin can't deduce it - "File was saved by unknown addon version"

**Comment by bsavery** [comment]
Ok, maybe the scenes need to be update.  I'll get a task made for that.

**Comment by bsavery** [comment]
Closing issue.  Please use the blender 2.80 plugin.
