### ISSUE TITLE
RPR v2.1.1 Hue/Saturation Node Bug

### ISSUE THREAD

**Issue by aledbrown** [Radeon-ProRender/Blender#8]
Adding the Hue Saturation Node between an Image Texture and the Shader with RPR seems to wash out all of the colour instead of doing what it should with the controls.

Please see example screenshots below in Cycles and RPR and the included .blend file for the setup.

Cycles Hue Sat Node Output (Correct):
<img width="1433" alt="01 Cycles Hue Sat Output Correct" src="https://user-images.githubusercontent.com/690500/70126470-01785400-1671-11ea-9da2-8c0dd8e7b379.png">

**RPR Hue Sat Node Output (Incorrect):**
<img width="1433" alt="02 RPR Hue Sat Node Output Incorrect" src="https://user-images.githubusercontent.com/690500/70126560-37b5d380-1671-11ea-91cd-0f61131a529d.png">

Cycles with the Nue Sat Node Removed (Correct):
<img width="1433" alt="04 Cycles Remove the Hue Sat Node" src="https://user-images.githubusercontent.com/690500/70126566-3b495a80-1671-11ea-9874-ad217b1fcfac.png">

RPR with the Nue Sat Node Removed (Correct):
<img width="1433" alt="03 RPR Remove the Hue Sat Node" src="https://user-images.githubusercontent.com/690500/70126562-384e6a00-1671-11ea-9d98-4234f4e63aab.png">

Sample file:
[RPR 211 Hue Saturation Node.blend.zip](https://github.com/Radeon-ProRender/Blender/files/3920892/RPR.211.Hue.Saturation.Node.blend.zip)

**Comment by bsavery** [comment]
This appears to be the bug.  However I don't think we'll get to this until early 2020 due to limitations in the current shaders.

**Comment by aledbrown** [comment]
This bug has largely been fixed as of RPR 2.2.12 however, one minor code change is required to make it compatible with Cycles. The default for the Hue slider should be 0.5. In RPR this is not the case.

I believe Line 1907 of nodes/blender_nodes.py needs to be:
`hue = self.get_input_value('Hue') - 0.5`

I am testing this change but so far it seems to be working as expected.

**Comment by bsavery** [comment]
Merged change.

**Comment by bsavery** [comment]
Thanks!
